name: Deploy Next.js Frontend to Azure

on:
  push:
    branches:
      - main

permissions:
  id-token: write # Required for requesting the JWT
  contents: read # Required for actions/checkout

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install & Build Frontend
        run: |
          npm install
          npm run build

      - name: Package Standalone Next.js App
        run: |
          # Copy public and static assets into the standalone folder to be served by server.js
          cp -r public .next/standalone/
          cp -r .next/static .next/standalone/.next/
          
          # Zip the standalone folder contents directly
          cd .next/standalone
          zip -r ../../deploy.zip .
          cd ../..

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_146BE3BF0C1049E095B2C63550639579 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6D6FF27214C34FCE9E9D040D929E3BDB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_96C6647C994B4EF2AC668B5BEBB5926E }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'mrlegezt-frontend'
          slot-name: 'Production'
          package: './deploy.zip'
